# Generated by Django 4.2.28 on 2026-02-18 04:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo del análisis', max_length=200)),
                ('analysis_type', models.CharField(choices=[('basic', 'Análisis Básico'), ('systematic_2d', 'Análisis Sistemático 2D'), ('control_3d', 'Análisis con Control 3D')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('config_params', models.JSONField(default=dict, help_text='Parámetros de configuración del análisis')),
                ('results_summary', models.JSONField(blank=True, default=dict, help_text='Resumen de resultados (estadísticas)', null=True)),
                ('csv_file_path', models.CharField(blank=True, help_text='Ruta al archivo CSV con resultados', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el análisis')),
            ],
            options={
                'verbose_name': 'Ejecución de Análisis',
                'verbose_name_plural': 'Ejecuciones de Análisis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SteadyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rs', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rd', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('alpha', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('delta', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('beta', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('eta', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('mu', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('c_star', models.FloatField(help_text='Concentración de células cancerosas en equilibrio')),
                ('s_star', models.FloatField(help_text='Concentración de células sanas en equilibrio')),
                ('i_star', models.FloatField(blank=True, help_text='Concentración de células inmunes en equilibrio', null=True)),
                ('eig1_real', models.FloatField()),
                ('eig1_imag', models.FloatField(default=0)),
                ('eig2_real', models.FloatField()),
                ('eig2_imag', models.FloatField(default=0)),
                ('eig3_real', models.FloatField(blank=True, null=True)),
                ('eig3_imag', models.FloatField(default=0)),
                ('unstable', models.BooleanField(default=False, help_text='True si el equilibrio es inestable')),
                ('max_real', models.FloatField(help_text='Máxima parte real de los autovalores')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steady_states', to='steady_states_app.analysisrun')),
            ],
            options={
                'ordering': ['-max_real', 'c_star'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('allee_type', models.CharField(choices=[('WEAK', 'Weak'), ('STRONG', 'Strong')], max_length=10)),
                ('mu', models.FloatField()),
                ('use_adaptive_control', models.BooleanField(default=False)),
                ('params', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Si está activo en scenarios.json')),
                ('steady_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='steady_states_app.steadystate')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='steadystate',
            index=models.Index(fields=['analysis_run', 'unstable'], name='steady_stat_analysi_313412_idx'),
        ),
        migrations.AddIndex(
            model_name='steadystate',
            index=models.Index(fields=['c_star', 's_star'], name='steady_stat_c_star_332533_idx'),
        ),
    ]
