# Generated by Django 4.2.28 on 2026-02-18 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steady_states_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='json_file_path',
            field=models.CharField(blank=True, help_text='Ruta al archivo JSON con resultados', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='processed_combinations',
            field=models.IntegerField(default=0, help_text='Número de combinaciones procesadas'),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='progress_message',
            field=models.TextField(blank=True, help_text='Mensaje de estado actual del análisis'),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='progress_percent',
            field=models.FloatField(default=0.0, help_text='Porcentaje de progreso (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='total_combinations',
            field=models.IntegerField(blank=True, help_text='Total de combinaciones de parámetros a procesar', null=True),
        ),
    ]
