# Generated by Django 4.2.28 on 2026-02-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steady_states_app', '0002_analysisrun_json_file_path_and_more'),
    ]

    operations = [
    ]
