"""
Django settings for rd_coupled_lab project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from typing import List, Optional

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Directorio del proyecto Allee (paquete steady_states/, código de simulación, etc.)
ALLEE_DIR = (BASE_DIR.parent / 'Models' / 'Allee').resolve()


def _rclone_googledrive_mount_bases() -> List[Path]:
    """
    Bases típicas del montaje rclone (~/googledrive).
    /root/googledrive solo si el proceso es root; si no, stat() ahí da PermissionError.
    """
    bases: List[Path] = [Path.home() / "googledrive"]
    try:
        if os.geteuid() == 0:
            bases.append(Path("/root/googledrive"))
    except AttributeError:
        # Windows u otro entorno sin geteuid
        pass
    return bases


def _rclone_drive_catalog_candidates() -> List[Path]:
    """
    Rutas típicas cuando Drive está montado con rclone (mount_google_drive.sh).
    Por defecto el script usa ~/googledrive; si se ejecuta como root suele ser /root/googledrive.
    Opcional: GOOGLE_DRIVE_MOUNT_POINT o GDRIVE_MOUNT_POINT.
    """
    bases: List[Path] = []
    mp = (os.environ.get("GOOGLE_DRIVE_MOUNT_POINT") or os.environ.get("GDRIVE_MOUNT_POINT") or "").strip()
    if mp:
        bases.append(Path(mp).expanduser().resolve())
    # Mismo usuario que corre Django; /root solo si es root (ver _rclone_googledrive_mount_bases).
    for b in _rclone_googledrive_mount_bases():
        try:
            r = b.resolve()
        except OSError:
            continue
        if r not in bases:
            bases.append(r)
    # Orden: rutas comprobadas en el montaje rclone real (p. ej. carpeta intermedia "Doctorado …").
    tails = [
        ("Doctorado Erick Serrato", "Resultados Paper", "estados_estacionarios", "steady_states_full_run.json"),
        ("Doctorado Erick Serrato", "Resultados paper", "estados_estacionarios", "steady_states_full_run.json"),
        ("My Drive", "Doctorado Erick Serrato", "Resultados Paper", "estados_estacionarios", "steady_states_full_run.json"),
        ("My Drive", "Doctorado Erick Serrato", "Resultados paper", "estados_estacionarios", "steady_states_full_run.json"),
        ("Resultados paper", "estados_estacionarios", "steady_states_full_run.json"),
        ("Resultados Paper", "estados_estacionarios", "steady_states_full_run.json"),
        ("My Drive", "Resultados paper", "estados_estacionarios", "steady_states_full_run.json"),
        ("My Drive", "Resultados Paper", "estados_estacionarios", "steady_states_full_run.json"),
    ]
    out: List[Path] = []
    for base in bases:
        for parts in tails:
            out.append(base.joinpath(*parts))
    return out


def _rclone_discovery_roots() -> List[Path]:
    roots: List[Path] = []
    mp = (os.environ.get("GOOGLE_DRIVE_MOUNT_POINT") or os.environ.get("GDRIVE_MOUNT_POINT") or "").strip()
    if mp:
        try:
            roots.append(Path(mp).expanduser().resolve())
        except OSError:
            pass
    for b in _rclone_googledrive_mount_bases():
        try:
            br = b.resolve()
        except OSError:
            continue
        if br not in roots:
            roots.append(br)
    return roots


def _discover_steady_states_full_run_json() -> Optional[Path]:
    """
    Si las rutas canónicas fallan, busca ``steady_states_full_run.json`` bajo el montaje rclone
    (nombre de carpeta distinto, otra jerarquía, etc.). Recorrido acotado para no recorrer todo Drive.
    """
    if not _running_under_wsl():
        return None
    fname = "steady_states_full_run.json"
    max_depth = 14
    max_visits_per_root = 4000
    for root in _rclone_discovery_roots():
        try:
            if not root.is_dir():
                continue
        except OSError:
            continue
        visits = 0
        try:
            for dirpath, dirnames, filenames in os.walk(root, topdown=True):
                visits += 1
                if visits > max_visits_per_root:
                    break
                try:
                    depth = len(Path(dirpath).resolve().relative_to(root).parts)
                except ValueError:
                    depth = 0
                if depth > max_depth:
                    dirnames[:] = []
                    continue
                dirnames[:] = [d for d in dirnames if not d.startswith(".")]
                if fname in filenames:
                    return (Path(dirpath) / fname).resolve()
        except OSError:
            continue
    return None


def _running_under_wsl() -> bool:
    try:
        with open("/proc/version", "r", encoding="utf-8", errors="ignore") as f:
            return "microsoft" in f.read().lower()
    except OSError:
        return False


def _reject_repo_packaged_steady_catalog(p: Path) -> bool:
    """
    No usar como catálogo el ``steady_states_full_run.json`` empaquetado sólo en el repo
    (Models/Allee/estados_estacionarios). La fuente operativa debe ser Drive / env explícito.
    """
    try:
        r = p.resolve()
        packaged = (ALLEE_DIR / "estados_estacionarios").resolve()
        return r.name == "steady_states_full_run.json" and packaged in r.parents
    except OSError:
        return False


def _resolve_scenarios_catalog_path() -> Path:
    """
    Catálogo de escenarios: solo ``steady_states_full_run.json`` (p. ej. en Drive).
    No se usa ``Models/Allee/scenarios.json`` como fuente de lectura.

    Prioridad:
    1. STEADY_STATES_CATALOG_JSON o SCENARIOS_JSON_PATH (env), si el archivo existe
       (se ignora si apunta al JSON sólo-local bajo ``Models/Allee/estados_estacionarios``).
    2. Montaje rclone (``/root/googledrive``, ``~/googledrive``, o env ``GOOGLE_DRIVE_MOUNT_POINT``)
    3. Google Drive vía ``/mnt/c/Users/.../Google Drive/...`` (app de escritorio en Windows)
    4. Si nada existe: ruta preferida para el mensaje de error en la UI (o la del env si estaba definida)
    """
    env = (
        os.environ.get("STEADY_STATES_CATALOG_JSON")
        or os.environ.get("SCENARIOS_JSON_PATH")
        or ""
    ).strip()
    env_path = Path(env).expanduser().resolve() if env else None
    if env_path is not None:
        try:
            if env_path.is_file() and not _reject_repo_packaged_steady_catalog(env_path):
                return env_path
        except OSError:
            pass
        # La variable apunta a una ruta que aún no existe: continuar con candidatos (p. ej. My Drive vs sin My Drive).
    home = Path.home()
    # "My Drive" / "Mi unidad": estructura habitual de Google Drive para escritorio (sin ella la ruta suele fallar).
    win_user = Path("/mnt/c/Users/Erick Serrato")
    wsl_drive_candidates = [
        win_user
        / "Google Drive"
        / "My Drive"
        / "Resultados paper"
        / "estados_estacionarios"
        / "steady_states_full_run.json",
        win_user
        / "Google Drive"
        / "My Drive"
        / "Resultados Paper"
        / "estados_estacionarios"
        / "steady_states_full_run.json",
        win_user
        / "Google Drive"
        / "Resultados paper"
        / "estados_estacionarios"
        / "steady_states_full_run.json",
        win_user
        / "Google Drive"
        / "Resultados Paper"
        / "estados_estacionarios"
        / "steady_states_full_run.json",
    ]
    home_candidates = [
        home / "Google Drive" / "My Drive" / "Resultados paper" / "estados_estacionarios" / "steady_states_full_run.json",
        home / "Google Drive" / "My Drive" / "Resultados Paper" / "estados_estacionarios" / "steady_states_full_run.json",
        home / "Google Drive" / "Resultados paper" / "estados_estacionarios" / "steady_states_full_run.json",
        home / "Google Drive" / "Resultados Paper" / "estados_estacionarios" / "steady_states_full_run.json",
        home / "Google Drive" / "Mi unidad" / "Resultados paper" / "estados_estacionarios" / "steady_states_full_run.json",
        home / "Google Drive" / "Mi unidad" / "Resultados Paper" / "estados_estacionarios" / "steady_states_full_run.json",
    ]
    # WSL: primero rclone (mount_google_drive.sh), luego /mnt/c/... (Google Drive de Windows), luego home.
    rclone_cands = _rclone_drive_catalog_candidates() if _running_under_wsl() else []
    if _running_under_wsl():
        candidates = rclone_cands + wsl_drive_candidates + home_candidates
    else:
        candidates = home_candidates + wsl_drive_candidates
    for p in candidates:
        try:
            if p.is_file() and not _reject_repo_packaged_steady_catalog(p):
                return p.resolve()
        except OSError:
            continue
    discovered = _discover_steady_states_full_run_json()
    if discovered is not None and not _reject_repo_packaged_steady_catalog(discovered):
        return discovered
    # Nada encontrado: devolver env (si había) para mensajes claros; si no, ruta típica preferida.
    if env_path is not None:
        try:
            if not env_path.is_file():
                return env_path
        except OSError:
            return env_path
        if not _reject_repo_packaged_steady_catalog(env_path):
            return env_path
    if _running_under_wsl() and rclone_cands:
        return rclone_cands[0].resolve()
    return (wsl_drive_candidates[0] if _running_under_wsl() else home_candidates[0]).resolve()

# Figuras PNG generadas por steady_states (p. ej. generate_figures_from_scenarios.py) → Models/Paper/figures
_figures_env = (os.environ.get('ALLEE_FIGURES_DIR') or '').strip()
FIGURES_DIR = (
    Path(_figures_env).expanduser().resolve()
    if _figures_env
    else (ALLEE_DIR.parent / 'Paper' / 'figures').resolve()
)
# Si FIGURES_DIR no existe (p. ej. Django en WSL y carpeta solo en /mnt/c/...), probar esta ruta al listar/servir PNG.
_figures_fb = (os.environ.get('ALLEE_FIGURES_DIR_FALLBACK') or '').strip()
FIGURES_DIR_FALLBACK = (
    Path(_figures_fb).expanduser().resolve()
    if _figures_fb
    else None
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1ldctf-_4ll+5q4al5_kt=#w6g(6p9#j6k=y57t)g0iv3nl=cf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Permitir acceso desde WSL


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    'steady_states_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rd_coupled_lab.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rd_coupled_lab.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (archivos subidos por usuarios)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración para integración con el módulo núcleo de estados estacionarios
STEADY_STATES_MODULE_PATH = str(ALLEE_DIR / 'steady_states' / 'steady_states.py')
# Lectura del catálogo del laboratorio → steady_states_full_run.json (Drive / env). No lee Models/Allee/scenarios.json.
SCENARIOS_JSON_PATH = str(_resolve_scenarios_catalog_path())
# Escritura opcional solo para el modal EE (archivo auxiliar local); no es la fuente del dashboard.
_write_catalog = (os.environ.get("SCENARIOS_JSON_WRITE_PATH") or "").strip()
SCENARIOS_JSON_WRITE_PATH = str(
    Path(_write_catalog).expanduser().resolve()
    if _write_catalog
    else (ALLEE_DIR / "scenarios.json").resolve()
)
# Valor por defecto para referencia; la resolución real (RESULTS_DIR en env + Drive + utils_paths)
# está en steady_states_app.lab_paths.get_lab_results_root().
RESULTS_DIR = os.environ.get('RESULTS_DIR') or str(ALLEE_DIR / 'results')

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'rd-coupled-lab-cache',
    }
}

# COOP solo tiene efecto en orígenes "potencialmente fiables" (HTTPS o localhost).
# Con http://<IP-de-WSL>:8000 Chrome ignora la cabecera y muestra aviso en consola.
if DEBUG:
    SECURE_CROSS_ORIGIN_OPENER_POLICY = None
